"""empty message

Revision ID: 1c90fe6c8053
Revises: 46fd6927b0a3
Create Date: 2019-10-15 08:39:29.928583

"""

# revision identifiers, used by Alembic.
revision = '1c90fe6c8053'
down_revision = '46fd6927b0a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    ### end Alembic commands ###
